sudo: required

services:
	- docker

before_install:
	- docker build -t makya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true makya/docker-react npm run test

language: generic



